# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastkafka-gen',
                'doc_host': 'https://airtai.github.io',
                'git_url': 'https://github.com/airtai/fastkafka-gen',
                'lib_path': 'fastkafka_gen'},
  'syms': {'fastkafka_gen.core': {'fastkafka_gen.core.foo': ('core.html#foo', 'fastkafka_gen/core.py')}}}
