# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/New_Project_Generator.ipynb.

# %% auto 0
__all__ = ['create_project']

# %% ../../nbs/New_Project_Generator.ipynb 1
from typing import *
from pathlib import Path
from yaspin import yaspin
import shutil


from .._code_generator.helper import download_and_extract_faststream_archive
from .._code_generator.constants import FASTSTREAM_TEMPLATE_ZIP_URL, FASTSTREAM_TEMPLATE_DIR_SUFFIX

# %% ../../nbs/New_Project_Generator.ipynb 3
def create_project(
    output_path: str,
) -> None:
    with yaspin(
        text="Creating a new FastStream project...", color="cyan", spinner="clock"
    ) as sp:
        with download_and_extract_faststream_archive(
            FASTSTREAM_TEMPLATE_ZIP_URL
        ) as extracted_path:
            shutil.copytree(
                    str(extracted_path / FASTSTREAM_TEMPLATE_DIR_SUFFIX),
                    output_path,
                    dirs_exist_ok=True,
                )

        sp.text = ""
        sp.ok(f" ✔ New FastStream project created.")
